spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: ${FIAP_USER}
    password: ${FIAP_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
